code_project_dir: /code_project_dir
work_project_dir: /work_project_dir
Rscript: /conda_path/envs/some_env/bin/Rscript
Rscript_cicero: /conda_path/envs/cicero/bin/Rscript
cCREgene_dir: 04.cCREgene
pmat_dir: pmat
cicero_dir: cicero
snap_file: snap.rds
meta_col: AllenAnnotConcat
n_ds: 2000
n_core: 2
group_file: groupList
peak_file: allpeak.bed
subclass_bpmat_file: binary.pmat.rds
L3_bpmat_file: L3.binary.pmat.rds
mm10_file: mm10.chrom.size.txt
tssUpDn1k_file: gencode.vM23.gene.tssUpDn1k.bed
peakannot_file: proximal.distal.peak.annot.bed
k_cicero: 50
reduct_cicero: "UMAP"
preprocess_cicero: "LSI"
debug: 0
allen_l2_cpm_file: allen.L2.cpm.rds
atac_subclass_cpm_file: subclass.cpm.rds
rdm_pdc_file: rdm.pdc.rds
pdc_file: proximal.distal.rds
chunk_size: 50000

