system: imac
python:
  imac: /Users/szu/mambaforge/bin/python
  tscc: /projects/ps-renlab/szu/miniconda3/envs/snATAC2/bin/python
  encoder: /projects/ps-renlab2/szu/miniconda3/envs/cicero/bin/python
Rscript:
  imac: /usr/local/bin/Rscript
  tscc: /projects/ps-renlab/szu/miniconda3/envs/snATAC2/bin/Rscript
  encoder: /projects/ps-renlab2/szu/miniconda3/envs/cicero/bin/Rscript
code_dir:
  imac: /Users/szu/git-recipes/mouseBrainAtlas/cembaV2
  tscc: /projects/ps-renlab2/szu/projects/CEMBA2
  encoder: /projects/ps-renlab2/szu/projects/CEMBA2
work_dir:
  imac: /Users/szu/git-recipes/mouseBrainAtlas/cembaV2
  tscc: /oasis/tscc/scratch/szu/projects/CEMBA2
  encoder: /projects/ps-renlab2/szu/projects/CEMBA2
homer:
  imac: /Users/szu/mambaforge/envs/bio/bin/findMotifsGenome.pl
  tscc: /projects/ps-renlab2/szu/miniconda3/envs/cicero/bin/findMotifsGenome.pl
  encoder: /projects/ps-renlab2/szu/miniconda3/envs/cicero/bin/findMotifsGenome.pl
subclass_order_meta: meta/subclass.order.hc.csv
local_dir: package/tasks/nmf
peak_nm_file: data/peaks.txt
cluster_nm_file: data/clusters.txt
mat_pbyc_h5: data/cpm.cbyp.ppdc.h5
tag: Intv2
out: nmf_Intv2
n_rerun: 2
mod_from: 150
mod_to: 151
mod_by: 1
use_detailed_mod: 1
detailed_mod: 40a80
mod_split: a
module: 150
