system: imac
project_dir:
  imac: /Users/szu/git-recipes/mouseBrainAtlas/CEMBA2
  encoder: /projects/ps-renlab/szu/projects/CEMBA2
  tscc: /projects/ps-renlab/szu/projects/CEMBA2
subset_dir: subset
callpeak_dir: callpeak
cemba_all_dataset: src/main/resource/cemba.sa2.dlt2.anndataset.h5ad
subset_barcode2group: src/main/resource/subset.barcode2group.csv

