n_ds: 1000
n_core: 2
mm10_file: meta/mm10.chrom.sizes.lite
tssUpDn1k_file: meta/gencode.vM23.gene.tssUpDn1k.bed
peakannot_file: 04.cCREgene/sa2.cicero/src/main/resource/mba.whole.sa2.peakOvlpTSS.proximal.distal.ciceroPeakCoord.bed
k_cicero: 50
reduct_cicero: "UMAP"
preprocess_cicero: "LSI"
debug: 0
atac_subclass_cpm_file: 04.cCREgene/sa2.cicero/out/sa2pdcsum/sa2.cpm.pmat.pbysc.distal.rds
rdm_pdc_file: 04.cCREgene/sa2.cicero/out/sa2pdcsum/sa2.rdm.g2p.pdc.rds
allen_l2_cpm_file: 04.cCREgene/sa2.cicero/out/sa2pdcsum/sa2.allen.avg.logCPM.gbysc.rds
pdc_file: 04.cCREgene/sa2.cicero/out/sa2pdcsum/sa2.g2p.pdc.pair.rds
chunk_size: 50000

